import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';
import '../../../core/theme/app_colors.dart';

class TermsOfServiceScreen extends StatelessWidget {
  const TermsOfServiceScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.backgroundPage,
      appBar: AppBar(
        backgroundColor: AppColors.backgroundCard,
        elevation: 0,
        surfaceTintColor: Colors.transparent,
        leading: IconButton(
          icon: const Icon(LucideIcons.arrowLeft, color: AppColors.ink),
          onPressed: () => Navigator.of(context).maybePop(),
        ),
        title: Text(
          'Terms of Service',
          style: GoogleFonts.sora(
            fontSize: 16,
            fontWeight: FontWeight.w700,
            color: AppColors.ink,
          ),
        ),
        bottom: const PreferredSize(
          preferredSize: Size.fromHeight(1),
          child: Divider(height: 1, color: AppColors.line),
        ),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Version & Effective Date Banner
              Container(
                width: double.infinity,
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                decoration: BoxDecoration(
                  color: AppColors.mint,
                  borderRadius: BorderRadius.circular(14),
                  border: Border.all(color: AppColors.teal.withValues(alpha: 0.2)),
                ),
                child: Row(
                  children: [
                    const Icon(LucideIcons.fileText, color: AppColors.teal, size: 20),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'NORI Terms of Service · Version 1.0',
                            style: GoogleFonts.sora(
                              fontSize: 13,
                              fontWeight: FontWeight.w700,
                              color: AppColors.teal,
                            ),
                          ),
                          const SizedBox(height: 2),
                          Text(
                            'Last Updated: October 2026 · Pending Formal Legal Review',
                            style: GoogleFonts.inter(
                              fontSize: 11,
                              color: AppColors.ink.withValues(alpha: 0.75),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 20),

              _buildSection(
                number: '1',
                title: 'Introduction and Scope',
                content:
                    'Welcome to NORI ("the Application"), an AI-powered personalized nutrition and lifestyle guidance companion tailored for Nigerian dietary patterns and wellness goals. By creating an account or accessing the Application, you acknowledge and agree to these Terms of Service. If you do not agree to these terms, do not register or use the Application.',
              ),

              _buildSection(
                number: '2',
                title: 'Not Medical Advice (Clinical Disclaimer)',
                content:
                    'NORI is strictly an informational, educational, and lifestyle guidance tool designed to assist with healthy eating habits, meal logging, and nutritional awareness.\n\n'
                    '• NORI IS NOT A LICENSED HEALTHCARE PROVIDER AND DOES NOT PROVIDE MEDICAL DIAGNOSIS, TREATMENT, OR CLINICAL PRESCRIPTIONS.\n'
                    '• Information, nutritional scores, and companion responses generated by NORI should never replace consultation with a qualified medical doctor, endocrinologist, or registered clinical dietitian.\n'
                    '• In the event of acute symptoms (e.g. chest pain, severe hypoglycemia, difficulty breathing), immediately seek emergency medical attention or contact Nigerian Emergency Services (199).',
                highlight: true,
              ),

              _buildSection(
                number: '3',
                title: 'User Registration & Biometric Information',
                content:
                    'To use NORI, you agree to provide truthful and accurate information during registration and health onboarding (including age, biological sex, weight, height, health conditions, and regional location). You are solely responsible for maintaining the confidentiality of your login credentials and session tokens.',
              ),

              _buildSection(
                number: '4',
                title: 'Multimodal Food Scanning & AI Guidance',
                content:
                    'NORI provides camera-based food recognition and nutritional estimation. While our models are specifically calibrated for Nigerian staples and recipes, portion size estimates, calories, and macronutrient breakdowns are approximations. You remain responsible for verifying meal safety, especially regarding food allergies and clinical diet restrictions.',
              ),

              _buildSection(
                number: '5',
                title: 'Acceptable Use and Restrictions',
                content:
                    'You agree not to misuse NORI, reverse-engineer proprietary algorithms, inject malicious code, attempt unauthorized access to other user accounts, or use the service for unlawful purposes. NORI reserves the right to suspend or terminate accounts that violate these terms.',
              ),

              _buildSection(
                number: '6',
                title: 'Data Ownership and Privacy',
                content:
                    'Your personal biometrics and dietary diary belong to you. NORI handles your data in accordance with our Privacy Policy. We do not sell or monetize your identifiable health records to third-party advertisers.',
              ),

              _buildSection(
                number: '7',
                title: 'Modifications to Service and Terms',
                content:
                    'We may periodically update these Terms to reflect technical improvements or legal requirements. Material updates will be communicated within the application. Continued use following notice constitutes acceptance of updated terms.',
              ),

              _buildSection(
                number: '8',
                title: 'Governing Law and Contact',
                content:
                    'These Terms are governed by the laws of the Federal Republic of Nigeria. For questions, concerns, or feedback regarding these Terms, contact support@nori.health.',
              ),
              const SizedBox(height: 24),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSection({
    required String number,
    required String title,
    required String content,
    bool highlight = false,
  }) {
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: highlight ? AppColors.dangerLight : AppColors.backgroundCard,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: highlight ? AppColors.coral.withValues(alpha: 0.3) : AppColors.line,
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                width: 24,
                height: 24,
                decoration: BoxDecoration(
                  color: highlight ? AppColors.coral : AppColors.teal,
                  shape: BoxShape.circle,
                ),
                alignment: Alignment.center,
                child: Text(
                  number,
                  style: const TextStyle(
                    color: Colors.white,
                    fontSize: 12,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: Text(
                  title,
                  style: GoogleFonts.sora(
                    fontSize: 14,
                    fontWeight: FontWeight.w700,
                    color: highlight ? AppColors.coral : AppColors.ink,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 10),
          Text(
            content,
            style: GoogleFonts.inter(
              fontSize: 13,
              height: 1.5,
              color: AppColors.ink.withValues(alpha: 0.85),
            ),
          ),
        ],
      ),
    );
  }
}
